spring:
  application:
    name: spring-base-app

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085